apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: init-test-ingress
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: ca-issuer
    cert-manager.io/duration: 300s
    #cert-manager.io/renew-before: 180s
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - host.k3d.internal
    secretName: host.k3d.internal
  rules: 
  - host: host.k3d.internal
    http:
      paths:
        - path: /init-test-ingress
          pathType: Prefix
          backend:
            service:
              name: init-test-app-service
              port:
                number: 443